### ISSUE TITLE
Treasure or Trade Goods

### ISSUE THREAD

**Issue by mageofthesands** [kristkos/KCTG-1e#2]
Suggestion for enhancement: Change the items into Treasure or Trade Goods type, depending on the item.  This will increase the use of KCTG with the [Loot Sheet ](https://github.com/Almightygir/fvtt-loot-sheet-npc-pf1) module and other things that calculate wealth.  
![TreasureChest](https://github.com/user-attachments/assets/af9179ef-4efa-4e4a-b873-39f42d73a228)

You can see in this screenshot that Selenium sells for full value after I changed it to Treasure.  Although it should probably be Trade Goods since it's raw material.  The Serpentine, by default, is worth only half.

**Comment by kristkos** [comment]
Due to the fact that the edits would need to be made across three different systems, and because this module was created by a dedicated member of the Pathfinder 1e community, it would be a bit unreasonable to ask for a complete remake of the items. Unfortunately, we're unable to make these changes at this time, and I do apologize.

If you'd like to make the edits yourself, the Mana Compendium Importer is a great tool for bulk editing, however, JSON knowledge might be needed.
